In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.9.2


In [43]:
from tensorflow.python.ops.init_ops import Initializer
class CustomLayer(tf.keras.layers.Layer):
    def __init__(self, units = 32, input_dim=32):
        super(CustomLayer, self).__init__()

        # parameters
        self.w = self.add_weight(
            shape = (input_dim, units), initializer = "random_normal", trainable=True
        )
        self.b = self.add_weight(
            shape = (units, ), initializer = "zeros", trainable = True
        )
        print(self.w)
        print(self.b)
    
    def call(self, inputs):
        return tf.matmul(inputs, self.w) + self.b

        # 

inputs = tf.Variable(
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ],
    dtype = "float"
)

print(inputs)
input_dim = inputs.shape[1]
custom_layer = CustomLayer(4,input_dim)
print(custom_layer)
print(custom_layer(inputs))
print("custom layer")
custom_layer.trainable_variables

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 4) dtype=float32, numpy=
array([[ 0.03544861,  0.09365223, -0.03911199, -0.01793247],
       [-0.04150108, -0.04895571, -0.01798448,  0.10171833]],
      dtype=float32)>
<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>
tf.Tensor(
[[-0.04755356 -0.00425919 -0.07508095  0.18550418]
 [-0.05965851  0.08513384 -0.18927386  0.35307592]
 [-0.07176346  0.1745269  -0.3034668   0.52064764]], shape=(3, 4), dtype=float32)
custom layer


[<tf.Variable 'Variable:0' shape=(2, 4) dtype=float32, numpy=
 array([[ 0.03544861,  0.09365223, -0.03911199, -0.01793247],
        [-0.04150108, -0.04895571, -0.01798448,  0.10171833]],
       dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>]

In [23]:
w = tf.Variable([[ 0.0202688 ,  0.03909454,  0.09400485,  0.04909619],
       [-0.01194151, -0.04327931,  0.04286179, -0.01722231]], dtype="float")
print(w)
tf.matmul(inputs, w)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=float32, numpy=
array([[ 0.0202688 ,  0.03909454,  0.09400485,  0.04909619],
       [-0.01194151, -0.04327931,  0.04286179, -0.01722231]],
      dtype=float32)>


<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-0.00361422, -0.04746408,  0.17972842,  0.01465157],
       [ 0.01304036, -0.05583361,  0.4534617 ,  0.07839932]],
      dtype=float32)>

In [24]:
(1*0.0202688) + (2*(-0.01194151))

-0.0036142200000000013

In [26]:
(3*0.03909454) + (4*(-0.04327931))

-0.055833620000000014

In [41]:
# non trainable arguments
class Linear(tf.keras.layers.Layer):

    def __init__(self, units=32, input_dim=32):
        super(Linear, self).__init__()
        self.w = self.add_weight(
            shape = (input_dim, units), initializer = "random_normal", trainable = False
        )
        self.b = self.add_weight(
            shape = (units, ), initializer = "zeros", trainable = False
        )

    def call(self, inputs):
        return tf.reduce_sum(inputs, axis=1)
        # return tf.matmul(inputs, self.w) + self.b
    
inputs = tf.Variable(
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ],
    dtype = "float"
)

print(inputs)
input_dim = inputs.shape[1]
linear = Linear(4,input_dim)
print(linear)
print(linear(inputs))
linear.trainable_variables

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)>
tf.Tensor([ 3.  7. 11.], shape=(3,), dtype=float32)


[]

In [66]:
# trainable parameters should be in build() method

class UsingBuild(tf.keras.layers.Layer):

    def __init__(self, units, name=None):
        super(UsingBuild, self).__init__(name=name)
        self.units = units
    
    def build(self, input_shape):
        print(f"input_shape is {input_shape}")
        self.w = self.add_weight(
            shape = (input_shape[-1], self.units), initializer = "random_normal", trainable = True, name="weights"
        )
        self.b = self.add_weight(
            shape = (self.units, ), initializer = "zeros", trainable = True, name="bais"
        )

    def call(self, inputs):
        return tf.matmul(inputs, self.w) + self.b
    

inputs = tf.Variable(
    [
        [0, 1, 3, 4, 5],
        [2, 3, 4, 5, 7],
        [3, 4, 9, 8, 7]
    ],
    dtype = 'float'
)
ub = UsingBuild(32)
print(ub(inputs))

input_shape is (3, 5)
tf.Tensor(
[[ 0.22340256 -0.37506363 -0.17111701  0.4356025  -0.04999616 -0.14916506
  -0.09368849  0.35280168  0.03178856 -0.28871992  0.06225333 -0.08193415
   0.20366377  0.20813937  0.04216195  0.47410348 -0.07598902 -0.06014659
   0.18219645 -0.2727355  -0.02524767 -0.46443677 -0.43005592 -0.5674378
  -0.14911117  0.29531768  0.41920015 -0.2378691  -0.15815374  0.5526229
  -0.91056216 -0.11781082]
 [ 0.5386747  -0.43203032 -0.1749022   0.630367   -0.03047334 -0.19265957
  -0.02136208  0.61581755 -0.05051629 -0.23029527 -0.09461592 -0.23642606
   0.4456762   0.21471177  0.0821692   0.5432055  -0.12238353 -0.00553431
   0.30592546 -0.18354811  0.186376   -0.70698774 -0.7446112  -0.6835253
  -0.1669229   0.39489707  0.54913133 -0.26316497 -0.40492824  0.7814899
  -0.8870546  -0.15793   ]
 [ 0.63472694 -0.66292745 -0.20880586  1.0064951   0.1281278  -0.45492375
   0.18128495  0.72605276  0.06323621 -0.17907758 -0.03336838 -0.60886556
   0.5397447   0.64668083  0.

In [67]:
for var in ub.trainable_variables:
    print(f"{var.name} ==> {var.shape}")

using_build_12/weights:0 ==> (5, 32)
using_build_12/bais:0 ==> (32,)


In [68]:
# we can use Layer in another layer

class MultiLayerNetwork(tf.keras.layers.Layer):

    def __init__(self):
        super(MultiLayerNetwork, self).__init__()
        self.linear1 =UsingBuild(32, "linear1")
        self.linear2 =UsingBuild(32, "linear2")
        self.linear3 =UsingBuild(1, "linear3")
    
    def call(self, inputs):
        x1 = self.linear1(inputs)
        x1 = tf.nn.relu(x1)

        x2 = self.linear2(x1)
        x2 = tf.nn.relu(x2)

        x3 = self.linear3(x2)
        return tf.nn.softmax(x3)

mln = MultiLayerNetwork()
print("weights", len(mln.weights))
print(mln(inputs))
print("weights", len(mln.weights))

weights 0
input_shape is (3, 5)
input_shape is (3, 32)
input_shape is (3, 32)
tf.Tensor(
[[1.]
 [1.]
 [1.]], shape=(3, 1), dtype=float32)
weights 6


In [70]:
for w in mln.weights:
    print(w.shape, w.name)

(5, 32) multi_layer_network_4/linear1/weights:0
(32,) multi_layer_network_4/linear1/bais:0
(32, 32) multi_layer_network_4/linear2/weights:0
(32,) multi_layer_network_4/linear2/bais:0
(32, 1) multi_layer_network_4/linear3/weights:0
(1,) multi_layer_network_4/linear3/bais:0
