In [1]:
import tensorflow as tf

printing the data instead of printing entire elements

In [ ]:
dataset = tf.data.Dataset.range(10)
dataset

<_RangeDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>

In [ ]:
for info in dataset.as_numpy_iterator():
    print(info)

0
1
2
3
4
5
6
7
8
9


if you wanna apply any functionality on dataset use -> apply

In [ ]:
def even(ds):
    return ds.filter(lambda info: info>=5)

for info in dataset.apply(even).as_numpy_iterator():
    print(info)

5
6
7
8
9


Batch

In [ ]:
for info in dataset.batch(3,True):
    print(info)

tf.Tensor([0 1 2], shape=(3,), dtype=int64)
tf.Tensor([3 4 5], shape=(3,), dtype=int64)
tf.Tensor([6 7 8], shape=(3,), dtype=int64)


Concatenating

In [ ]:
foo = tf.data.Dataset.from_tensors("foo").repeat()
bar = tf.data.Dataset.from_tensors("bar").repeat()
baz = tf.data.Dataset.from_tensors("baz").repeat()

choice = tf.data.Dataset.range(3).repeat(3)


dataset = tf.data.Dataset.choose_from_datasets([foo,bar,baz],choice)
for info in dataset.as_numpy_iterator():
    print(info)

b'foo'
b'bar'
b'baz'
b'foo'
b'bar'
b'baz'
b'foo'
b'bar'
b'baz'


In [ ]:
ds1 = tf.data.Dataset.range(3)
ds2 = tf.data.Dataset.range(3,7)
ds = ds1.concatenate(ds2)
for info in ds.as_numpy_iterator():
    print(info)

0
1
2
3
4
5
6


In [ ]:
# ds = tf.data.Dataset.from_tensors([
#     "Hello Madam",
#     "Y are you so mad at me",
#     "listen to me",
#     "Let me explain",
#     "Bye bye cute"
# ])
# print(type(ds))
# print(list(ds.batch(1,True).as_numpy_iterator()))

# dataset = tf.data.Dataset.range(10).batch(3,True)
# print(list(tf.data.Dataset.range(10).as_numpy_iterator()))
# for info in dataset: #.batch(2,):
#     print(info)
#     print(len(info))
#
data_url = "https://storage.googleapis.com/download.tensorflow.org/data/stack_overflow_16k.tar.gz"
so_file = tf.keras.utils.get_file(
    origin=data_url,
    untar=True)
print(so_file)

# vector_layer = tf.keras.layers.TextVectorization()

/root/.keras/datasets/stack_overflow_16k


In [ ]:
from pathlib import Path

SO_FILE = Path(so_file).parent
print(SO_FILE)

/root/.keras/datasets


In [ ]:
train_ds = SO_FILE/'train'
print(train_ds)

/root/.keras/datasets/train


In [ ]:
dataset = tf.keras.utils.text_dataset_from_directory(train_ds)

Found 8000 files belonging to 4 classes.
32


In [ ]:
vector_layer = tf.keras.layers.TextVectorization(output_mode='int')

data = dataset.map(lambda text, labels: text)
ds = vector_layer.adapt(data)

In [ ]:
vector_layer.vocabulary_size()

122199

In [ ]:
vector_layer.get_vocabulary()[:10]

['', '[UNK]', 'the', 'i', 'to', 'a', 'is', 'in', 'and', 'of']

In [ ]:
vector_layer(["Hello PYTHON", "java", "print"])

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[ 536, 2398],
       [1146,    0],
       [  77,    0]])>

In [ ]:
vector_layer.get_vocabulary()[1]

'hello'

In [ ]:
embd1 = tf.keras.layers.Embedding(vector_layer.vocabulary_size(), 64)


In [ ]:
embd1(122198)

<tf.Tensor: shape=(64,), dtype=float32, numpy=
array([ 0.02149076,  0.04016925,  0.00918638,  0.00848794,  0.0313055 ,
        0.02765513, -0.02126541, -0.02876803, -0.02362537,  0.02279221,
       -0.02531466,  0.02709771, -0.03576758, -0.04206804,  0.03601971,
       -0.01117323, -0.01298866,  0.00856166, -0.01851773, -0.01018571,
        0.0215295 , -0.04469781, -0.03191525, -0.02778369, -0.01472554,
        0.04966709, -0.00046244, -0.01609677, -0.02017015, -0.03263613,
        0.03227068,  0.04569366, -0.00426114, -0.02181348, -0.02480515,
       -0.04003732, -0.02565098,  0.04658866, -0.02147175,  0.02519914,
        0.01051618, -0.03657414,  0.01167037,  0.04769851, -0.04218898,
        0.01063158,  0.04624077, -0.04773209, -0.03110614,  0.00719946,
       -0.03213245,  0.04907903,  0.01653958, -0.01480908,  0.03775721,
        0.00404842,  0.01820997, -0.04068135, -0.00527833,  0.01003792,
       -0.0306405 ,  0.00041758,  0.03761018,  0.04219332], dtype=float32)>

In [3]:
tf.constant("Thanks 😊")

<tf.Tensor: shape=(), dtype=string, numpy=b'Thanks \xf0\x9f\x98\x8a'>

In [4]:
tf.constant([u"You're", u"welcome!"]).shape

TensorShape([2])

In [5]:
# Unicode string, represented as a UTF-8 encoded string scalar.
text_utf8 = tf.constant(u"语言处理")
text_utf8

<tf.Tensor: shape=(), dtype=string, numpy=b'\xe8\xaf\xad\xe8\xa8\x80\xe5\xa4\x84\xe7\x90\x86'>

In [6]:
text_utf16 = tf.constant(u"语言处理".encode("UTF-16-BE"))
text_utf16

<tf.Tensor: shape=(), dtype=string, numpy=b'\x8b\xed\x8a\x00Y\x04t\x06'>

In [9]:
tf.constant([ord(char) for char in u"语言处理"])

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([35821, 35328, 22788, 29702], dtype=int32)>

In [13]:
decode_num = tf.strings.unicode_decode(text_utf8,input_encoding='UTF-8')

In [15]:
tf.strings.unicode_encode(decode_num,output_encoding='UTF-8')


<tf.Tensor: shape=(), dtype=string, numpy=b'\xe8\xaf\xad\xe8\xa8\x80\xe5\xa4\x84\xe7\x90\x86'>

In [16]:
tf.strings.unicode_transcode(text_utf8,
                             input_encoding='UTF8',
                             output_encoding='UTF-16-BE')

<tf.Tensor: shape=(), dtype=string, numpy=b'\x8b\xed\x8a\x00Y\x04t\x06'>

In [17]:
data = [u'hÃllo', u'What is the weather tomorrow', u'Göödnight', u'😊']
data_utf8 = [item.encode("UTF-8") for item in data]
data_utf8

[b'h\xc3\x83llo',
 b'What is the weather tomorrow',
 b'G\xc3\xb6\xc3\xb6dnight',
 b'\xf0\x9f\x98\x8a']

In [20]:
data_decode = tf.strings.unicode_decode(data_utf8, input_encoding='UTF-8')
for decoded in data_decode.to_list():
    print(decoded)

[104, 195, 108, 108, 111]
[87, 104, 97, 116, 32, 105, 115, 32, 116, 104, 101, 32, 119, 101, 97, 116, 104, 101, 114, 32, 116, 111, 109, 111, 114, 114, 111, 119]
[71, 246, 246, 100, 110, 105, 103, 104, 116]
[128522]


In [22]:
data_decode.to_tensor(default_value=-1)

<tf.Tensor: shape=(4, 28), dtype=int32, numpy=
array([[   104,    195,    108,    108,    111,     -1,     -1,     -1,
            -1,     -1,     -1,     -1,     -1,     -1,     -1,     -1,
            -1,     -1,     -1,     -1,     -1,     -1,     -1,     -1,
            -1,     -1,     -1,     -1],
       [    87,    104,     97,    116,     32,    105,    115,     32,
           116,    104,    101,     32,    119,    101,     97,    116,
           104,    101,    114,     32,    116,    111,    109,    111,
           114,    114,    111,    119],
       [    71,    246,    246,    100,    110,    105,    103,    104,
           116,     -1,     -1,     -1,     -1,     -1,     -1,     -1,
            -1,     -1,     -1,     -1,     -1,     -1,     -1,     -1,
            -1,     -1,     -1,     -1],
       [128522,     -1,     -1,     -1,     -1,     -1,     -1,     -1,
            -1,     -1,     -1,     -1,     -1,     -1,     -1,     -1,
            -1,     -1,     -1,     -1